### ISSUE TITLE
Support Firefox 133+ Mica

### ISSUE THREAD

**Issue by Ingan121** [angelbruni/Geckium#384]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 10 22H2 w/21H2to7

### What would you like to suggest for Geckium?

Since Firefox 133 brought back the native title bars, it is now possible to use Aero on stock Firefox again.

To enable mica, set `widget.windows.mica` to `true` in `about:config`. Works even on Windows 10.

Other configs that are often suggested but don't seem necessary:
`browser.tabs.allow_transparent_browser`
`browser.theme.native-theme`

### Additional Context

My simple modifications to get Aero working on 133 with Public Beta 1.11:
Comment out background-color lines in geckiumChrome.css:954-960.
Add these in userChrome.css
```css
#navigator-toolbox {
border-top-color: transparent !important;
}

/* Hardcoded for Win7 button style with 100% DPI */
/* Adjust to fit your button sizes */
.titlebar-buttonbox-container {
height: 20px !important;
opacity: 0;
}

.titlebar-button {
padding: 0 8px !important;
}

.titlebar-close {
padding: 0px 17px !important;
}
```

Result:
![firefox_diT1btdclq](https://github.com/user-attachments/assets/7018a42e-ad2a-4c85-83fa-9295480f9478)
(Using 21H2to7+Dark7+AWM+OpenGlass)

Title bar button hover effects only work when unmaximized, unfortunately.
